# Generated by Django 3.2.3 on 2021-06-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plezmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requested_app',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=150)),
                ('app_desc', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'close'), (3, 'working'), (4, 'done')], default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
