# Generated by Django 3.2.3 on 2021-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plezmoapp', '0002_requested_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='verified',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
