# Generated by Django 3.2.3 on 2021-06-16 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plezmoapp', '0003_user_data_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('error', models.CharField(max_length=255)),
                ('error_to', models.CharField(max_length=30)),
                ('error_from', models.CharField(max_length=30)),
                ('action', models.CharField(default='Not Taken', max_length=25)),
                ('timeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.EmailField(default='fake@mail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='logo',
            field=models.CharField(default='/assets/img/svg/D.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='user_data',
            name='one_time_password',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=250)),
                ('logo', models.CharField(default='/assets/img/svg/D.svg', max_length=100)),
                ('timeStamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('logo', models.CharField(default='/assets/img/svg/D.svg', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plezmoapp.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plezmoapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
